import { SeedContext } from '../types';

export const resetDatabase = async (ctx: SeedContext): Promise<void> => {
  await ctx.prisma.$executeRawUnsafe(`
    TRUNCATE TABLE
      "OpeningBalanceLine",
      "OpeningBalanceBatch",
      "JournalLine",
      "JournalEntry",
      "AccountingPeriod",
      "FiscalYear",
      "AccountingEntrySequence",
      "AccountingConfigurationJournal",
      "AccountingConfigurationAccount",
      "AccountingSetup",
      "AccountingConfiguration",
      "AccountingJournal",
      "AccountingAccount",
      "AccountingTemplateAccount",
      "AccountingTemplate",
      "PaymentTermLine",
      "CustomerProfile",
      "SupplierProfile",
      "BusinessPartnerAddress",
      "BusinessPartnerContact",
      "PaymentTerm",
      "BusinessPartner",
      "InvoiceItem",
      "Invoice",
      "Product",
      "Expense",
      "InstallmentPayment",
      "InstallmentSchedule",
      "InstallmentContract",
      "DeferredPayment",
      "DeferredSale",
      "Notification",
      "DeviceToken",
      "AuditLog",
      "Balance",
      "LedgerEntry",
      "Customer",
      "Supplier",
      "Employee",
      "SubscriptionPayment",
      "CompanySubscription",
      "Plan",
      "StaffPermission",
      "RefreshToken",
      "PasswordResetToken",
      "User",
      "Company"
    RESTART IDENTITY CASCADE;
  `);
};
